### ISSUE TITLE
Checklist 

### ISSUE THREAD

**Issue by apurbaanik** [apurbaanik/topMusicArtists#1]
Task List:
- [x] Create a repository
- [x] Add topMusicArtists.java
- [x] Create a README file with a description.
- [x] Add the input and output files.
- [x] Submit the link in MS Teams.

**Comment by apurbaanik** [comment]
Uploaded source code
